### ISSUE TITLE
Aircraft can request and receive multiple oceanic clearances

### ISSUE THREAD

**Issue by erikquinn** [vatsimnetwork/nattrak#26]
Though I don't believe they can have multiple requests, aircraft can receive multiple oceanic clearances. They request one, get a clearance, can request another, which can also result in a second clearance. Both the active request and the pending RCL were shown in their respective lists. Shouldn't it not be possible to have duplicates?

Some thought should go into how to proceed:
- should it reject the attempt to request a new clearance when one is active?
- should there be a way to request a change to a clearance you've already received?
- should it show the current clearance and say "contact ATC if any change"?
- should they be able to cancel their old clearance and request a new one?
- should the "active clearances" list exclude the "old" clearance, and only show the latest one?
- etc

Probably safe to assume there's no way to be able to see anything this far back, but the specific example that brought this issue was for the flight below, during CTP 22E:

https://statsim.net/flights/flight/?flightid=10247131
- AIC2887
- KIAD-LOWW
- OCT 22, 2022
- requested ELSIR NATU @ 1700, cleared 1631
- later also requested ELSIR NATU @ 1845

**Comment by liessdow** [comment]
It should already reject people submitting a request if they already have a pending one. My idea:

- Cooldown of 30 minutes for requesting a new clearance in general. 30 minutes is best IMO because it can account for someone's sim crashing or them needing to restart within 30 minutes of the clearance in the case they're departing from CYYT or similar airport.
- Provide a "request change" button for clearances, though I'd honestly prefer people just used voice for this.
- Providing a warning after 30 minutes if there is an RCL from that CID with the same callsign within 5-6 hours.
