### ISSUE TITLE
RCL notify new ETA

### ISSUE THREAD

**Issue by lieselwd** [vatsimnetwork/nattrak#90]
As requested after CTP April 2023, pilots should be able to submit an updated ETA via natTrak in conjunction with their existing clearance.

Perhaps this notification could be shown in the pending RCL table for the clearance controller with an icon or different cell shade.

**Comment by Paulmc98** [comment]
If possible, can a function be built in so that entry sectors/FIRs can pass updated boundary estimates?

Ideally, this would be done via coordination/phone call from the domestic sector/FIR and the Oceanic controller would send a new oceanic clearance which would be received by the pilot and domestic controller.
